# Generated by Django 2.2 on 2020-06-09 18:26

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='e_City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('city', 'City'), ('town', 'Town'), ('village', 'Village'), ('other', 'Other')], max_length=15)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='e_Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_field', message='', regex='^[a-zA-Z0-9]*$')])),
                ('Name', models.CharField(max_length=20)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('capital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_Country_capital', to='rivercureportal.e_City')),
            ],
        ),
        migrations.CreateModel(
            name='e_District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_field', message='', regex='^[a-zA-Z0-9]*$')])),
                ('Name', models.CharField(max_length=20)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('capital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_District_capital', to='rivercureportal.e_City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_District_country', to='rivercureportal.e_Country')),
            ],
        ),
        migrations.CreateModel(
            name='e_Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('capital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_Municipality_capital', to='rivercureportal.e_City')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_Municipality_district', to='rivercureportal.e_District')),
            ],
        ),
        migrations.CreateModel(
            name='e_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('Name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('emails', models.EmailField(max_length=254)),
                ('phoneNumbers', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='e_Parish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_Parish_municipality', to='rivercureportal.e_Municipality')),
            ],
        ),
        migrations.CreateModel(
            name='e_Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('waterAuthority', 'WaterAuthority'), ('municipality', 'Municipality'), ('researchLab', 'ResearchLab'), ('partner', 'Partner'), ('other', 'Other')], max_length=15)),
                ('sector', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_Organization_city', to='rivercureportal.e_City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_Organization_country', to='rivercureportal.e_Country')),
            ],
        ),
        migrations.CreateModel(
            name='e_HydroFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('river', 'River'), ('estuary', 'Estuary'), ('lake', 'Lake'), ('riverBasin', 'RiverBasin'), ('drainageBasin', 'DrainageBasin'), ('dam', 'Dam')], max_length=15)),
                ('area', models.DecimalField(decimal_places=2, max_digits=5)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('PartOf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_HydroFeature_PartOf', to='rivercureportal.e_HydroFeature')),
                ('flowsInto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_HydroFeature_flowsInto', to='rivercureportal.e_HydroFeature')),
            ],
        ),
        migrations.AddField(
            model_name='e_city',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_City_municipality', to='rivercureportal.e_Municipality'),
        ),
    ]
