name: Django CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgis/postgis:12-2.5
                env:
                    POSTGRES_DB: rcp_db
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                ports:
                    - 5432:5432
                # needed because the postgres container does not provide a healthcheck
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.7
              uses: actions/setup-python@v2
              with:
                  python-version: 3.7
            - name: Prepare database and install geo dependencies
              run: |
                  sudo apt-get install libpq-dev
                  sudo apt-get install gdal-bin
            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements/prod.txt
            - name: Run Migrations
              env:
                  DATABASE_NAME: rcp_db
                  DATABASE_USER: postgres
                  DATABASE_PASSWORD: postgres
                  DATABASE_HOST: localhost
                  DATABASE_PORT: 5432
              run: |
                  python manage.py migrate
            - name: Collect static
              run: |
                  mkdir static
                  python manage.py collectstatic
              env:
                  DATABASE_NAME: rcp_db
                  DATABASE_USER: postgres
                  DATABASE_PASSWORD: postgres
                  DATABASE_HOST: localhost
                  DATABASE_PORT: 5432
            - name: Run Tests
              env:
                  DATABASE_NAME: rcp_db
                  DATABASE_USER: postgres
                  DATABASE_PASSWORD: postgres
                  DATABASE_HOST: localhost
                  DATABASE_PORT: 5432
              run: |
                  python manage.py test
